### ISSUE TITLE
Operator crashs if BFD not set in a gateway CR

### ISSUE THREAD

**Issue by LionelJouin** [Nordix/Meridio-Operator#37]
Here is the logs:
```
2021-11-04T13:59:23.371807831Z stderr F panic: runtime error: invalid memory address or nil pointer dereference
2021-11-04T13:59:23.371841355Z stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x161b2e6]
2021-11-04T13:59:23.371852728Z stderr F 
2021-11-04T13:59:23.371862904Z stderr F goroutine 617 [running]:
2021-11-04T13:59:23.371879588Z stderr F github.com/nordix/meridio-operator/controllers/trench.writBfdInGateway(0xc0000c4ab0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2021-11-04T13:59:23.371909213Z stderr F 	/workspace/controllers/trench/configmap.go:249 +0x26
2021-11-04T13:59:23.371939749Z stderr F github.com/nordix/meridio-operator/controllers/trench.(*ConfigMap).getGatewaysData(0xc000a20150, 0xc000c1fb80, 0xc000293f00, 0xf, 0x10, 0x0)
2021-11-04T13:59:23.371949559Z stderr F 	/workspace/controllers/trench/configmap.go:236 +0x425
2021-11-04T13:59:23.371955523Z stderr F github.com/nordix/meridio-operator/controllers/trench.(*ConfigMap).getAllData(0xc000a20150, 0x15, 0xc0008963c0, 0xc0009fbd40)
2021-11-04T13:59:23.371970141Z stderr F 	/workspace/controllers/trench/configmap.go:139 +0xc5
2021-11-04T13:59:23.371986458Z stderr F github.com/nordix/meridio-operator/controllers/trench.(*ConfigMap).getDesiredStatus(0xc000a20150, 0x0, 0x0, 0x0)
2021-11-04T13:59:23.371995164Z stderr F 	/workspace/controllers/trench/configmap.go:115 +0xb8
2021-11-04T13:59:23.372003988Z stderr F github.com/nordix/meridio-operator/controllers/trench.(*ConfigMap).getAction(0xc000a20150, 0x0, 0x0)
2021-11-04T13:59:23.372019236Z stderr F 	/workspace/controllers/trench/configmap.go:374 +0x12f
2021-11-04T13:59:23.372033856Z stderr F github.com/nordix/meridio-operator/controllers/trench.Meridio.ReconcileAll(0xc0003fa408, 0xc000781998, 0xc000dee780, 0xc000dee918, 0xc000deedc8, 0xc000def1a0, 0xc000defb48, 0xc000defe00, 0xc000a20150, 0x0, ...)
2021-11-04T13:59:23.372043826Z stderr F 	/workspace/controllers/trench/resources.go:87 +0x1a4
2021-11-04T13:59:23.372067558Z stderr F github.com/nordix/meridio-operator/controllers/trench.(*TrenchReconciler).Reconcile(0xc000795a40, 0x1ba1e78, 0xc00097bc80, 0xc000140839, 0x3, 0xc000140858, 0x8, 0xc00097bc80, 0xc000030000, 0x1822060, ...)
2021-11-04T13:59:23.372077215Z stderr F 	/workspace/controllers/trench/trench_controller.go:83 +0x408
2021-11-04T13:59:23.372086313Z stderr F sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004e75e0, 0x1ba1dd0, 0xc00027c000, 0x17df6a0, 0xc000844000)
2021-11-04T13:59:23.372103882Z stderr F 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:298 +0x30d
2021-11-04T13:59:23.372113174Z stderr F sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004e75e0, 0x1ba1dd0, 0xc00027c000, 0x1a36400)
2021-11-04T13:59:23.372121968Z stderr F 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:253 +0x205
2021-11-04T13:59:23.372131041Z stderr F sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc000321970, 0xc0004e75e0, 0x1ba1dd0, 0xc00027c000)
2021-11-04T13:59:23.372147694Z stderr F 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:214 +0x6b
2021-11-04T13:59:23.372154899Z stderr F created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
2021-11-04T13:59:23.372160526Z stderr F 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:210 +0x425
```
[0.log](https://github.com/Nordix/Meridio-Operator/files/7475385/0.log)

Here is the CRs used:
[all.yaml.txt](https://github.com/Nordix/Meridio-Operator/files/7475393/all.yaml.txt)

**Comment by mandydydy** [comment]
This happens due to webhook is not working. 
Probably introduced when I change the scope of the operator. Just tried the latest image with old yaml files and saw webhooks are working.

**Comment by mandydydy** [comment]
https://github.com/Nordix/Meridio-Operator/pull/38
